name: tensor_new
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - appdirs=1.4.4
  - attrs=21.4.0
  - black=19.10b0
  - blas=1.0
  - bottleneck=1.3.5
  - ca-certificates=2022.07.19
  - certifi=2022.9.14
  - click=8.0.4
  - intel-openmp=2021.4.0
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mypy_extensions=0.4.3
  - ncurses=6.3
  - numexpr=2.8.3
  - numpy-base=1.23.1
  - openssl=1.1.1q
  - packaging=21.3
  - pandas=1.4.4
  - pathspec=0.9.0
  - pip=21.2.4
  - pyparsing=3.0.9
  - python=3.8.13
  - python-dateutil=2.8.2
  - pytz=2022.1
  - readline=8.1.2
  - regex=2022.7.9
  - setuptools=61.2.0
  - six=1.16.0
  - sqlite=3.38.3
  - tk=8.6.11
  - toml=0.10.2
  - typed-ast=1.4.3
  - typing_extensions=4.3.0
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
  - pip:
    - absl-py==1.0.0
    - cycler==0.11.0
    - flatbuffers==2.0
    - fonttools==4.33.3
    - gast==0.4.0
    - grpcio==1.46.3
    - h5py==3.7.0
    - kiwisolver==1.4.2
    - matplotlib==3.5.2
    - numpy==1.22.4
    - pillow==9.1.1
    - tensorflow==2.7.0
    - tensorflow-estimator==2.7.0
    - typing-extensions==4.2.0
    - wrapt==1.14.1
