name: null

channels:
  - conda-forge
  - defaults

dependencies:
  - ccache
  - cmake
  - nvcc_linux-64=11.0
  - pip
  - pip:
    - tensorflow-gpu==2.7.*
    - -r file:requirements.txt
  - python=3.8
